Add nighly build update to web update scripts

diff --git a/sdcard/firmware/scripts/update/webupdate b/sdcard/firmware/scripts/update/webupdate
--- a/sdcard/firmware/scripts/update/webupdate
+++ b/sdcard/firmware/scripts/update/webupdate
@@ -7,26 +7,77 @@ WEBSITETGZ="/tmp/sd/website.tgz"
 WEBSITESUM="/tmp/sd/website.md5sum"
 WEBSITEDIR="/tmp/sd/firmware/www"
 
+## Set the curl command depending on local or camera
+if [ "$( uname -m )" == "armv5tel" ]
+then
+    CURL='curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -qs '
+    WGET='/tmp/sd/firmware/bin/wget --ca-certificate /tmp/sd/firmware/etc/ssl/cacert.pem '
+else
+    CURL='curl -qs '
+    WGET='wget '
+fi
 
-log() { echo "ERROR: ${*}" > /dev/stderr; }
+log() { echo "*** ${*}" > /dev/stderr; }
 
-die() { log "${*}"; exit 1; }
+die() { log "ERROR: ${*}"; exit 1; }
 
 
-download()
+rollback()
 {
-    local WEBSITE_URLS="$( curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -s https://api.github.com/repos/miicam/miicamweb/releases/latest | jq '.assets | to_entries[] | .value.browser_download_url' )"
+    if [ -d "${WEBSITEDIR}.old" ]
+    then
+        echo "*** Removing older rollback leftovers if present"
+        [ -d "${WEBSITEDIR}.broken" ] && rm -rf "${WEBSITEDIR}.broken"
 
-    [ "x${WEBSITE_URLS}" == "x" ] || die "Website content urls not found! Exiting upgrade"
+        echo "*** Moving ${WEBSITEDIR}.old back to ${WEBSITEDIR}"
+        mv "${WEBSITEDIR}" "${WEBSITEDIR}.broken" \
+        && mv "${WEBSITEDIR}.old" "${WEBSITEDIR}" \
+        && echo "*** Rollback completed"
+    else
+        echo "*** I'm sorry but a rollback is not possible"
+        echo "*** The ${WEBSITEDIR}.old cannot be found."
+        exit 1
+    fi
+}
 
+
+###################################################################
+## Download and Update functions to download latest release      ##
+###################################################################
+
+check_versions()
+{
+    ## Get versions of current and latest
+    local LATEST_VERSION="$(  webversion --latest  )" || die "Failed to retrieve the tag of the latest version"
+    local CURRENT_VERSION="$( webversion --current )" || die "Failed to retrieve the tag of the current version"
+
+    echo "*** Current version is: $CURRENT_VERSION"
+    echo "***  Latest version is: $LATEST_VERSION"
+
+    ## Download if a newer version is available
+    if [ "$LATEST_VERSION" -eq "$CURRENT_VERSION" ] ;
+    then
+        echo "*** You are already using the latest version available"
+        exit 0
+    fi
+}
+
+download_release()
+{
+    echo "Getting latest website download location"
+    local WEBSITE_URLS="$( ${CURL} https://api.github.com/repos/miicam/miicamweb/releases/latest | jq '.assets | to_entries[] | .value.browser_download_url' )"
+
+    [ "x${WEBSITE_URLS}" == "x" ] && die "Website content urls not found! Exiting upgrade"
+
+    echo "Removing older downloads"
     [ -f "${WEBSITETGZ}" ] && rm "${WEBSITETGZ}"
     [ -f "${WEBSITESUM}" ] && rm "${WEBSITESUM}"
 
+    echo "Downloading latest release files"
     cd /tmp/sd
-
     for URL in ${WEBSITE_URLS}
     do
-        /tmp/sd/firmare/bin/wget -q -t 5 -T 10 -c "$URL" || die "Failed to download from $URL"
+        ${WGET} -q -t 5 -T 10 -O "${WEBSITETGZ}" -c "$URL" || die "Failed to download from $URL"
     done
 
     [ -f "${WEBSITETGZ}" ] || die "Failed to download ${WEBSITETGZ}"
@@ -35,8 +86,7 @@ download()
     return 0
 }
 
-
-checksum()
+verify_release()
 {
     [ -f "${WEBSITESUM}" ] || die "File ${WEBSITESUM} not found!"
 
@@ -50,38 +100,21 @@ checksum()
         echo "Actual Sum: $( md5sum ${WEBSITESUM} )"
         return 1
     fi
+
 }
 
-
-main()
+update_release()
 {
-    if [ "$INPUT" != "--update" ]
-    then
-        echo "Usage: $0 --update"
-        echo "Update the web interface if needed"
-        exit 0
-    fi
-
-    ## Get versions of current and latest
-    local LATEST_VERSION="$(  webversion --latest  )" || die "Failed to retrieve the tag of the latest version"
-    local CURRENT_VERSION="$( webversion --current )" || die "Failed to retrieve the tag of the current version"
-
-    echo "*** Current version is: $CURRENT_VERSION"
-    echo "*** Latest version is:  $LATEST_VERSION"
-
-    ## Download if a newer version is available
-    if [ "$LATEST_VERSION" -gt "$CURRENT_VERSION" ] ;
+    if check_versions
     then
         echo "*** Downloading the latest webui release"
-        download || die "Failed to download the latest web ui"
-        checksum || die "Failed to match the md5sum"
-    else
-        echo "*** You are using the latest available version"
-        exit 0
+        download_release
+        verify_release
     fi
 
     ## Create the new webdir
-    test -d "${WEBSITEDIR}.new" || mkdir "${WEBSITEDIR}.new"
+    test -d "${WEBSITEDIR}.new" && rm -rf "${WEBSITEDIR}.new"
+    mkdir "${WEBSITEDIR}.new" || die "*** F"
 
     ## Remove the backup dest dir
     test -d "${WEBSITEDIR}.old" && rm -rf "${WEBSITEDIR}.old"
@@ -90,8 +123,8 @@ main()
     if [ -f "$WEBSITETGZ" ]
     then
         echo "*** Unpacking $WEBSITETGZ"
-        tar xzf "$WEBSITETGZ" -C "/tmp/sd/${WEBSITEDIR}.new" || die "Failed to unpack $WEBSITETGZ"
-        NEWVERSION="$( webversion --file "/tmp/sd/${WEBSITEDIR}.new/public/static/version.json" )"
+        tar xzf "$WEBSITETGZ" -C "${WEBSITEDIR}.new" || die "Failed to unpack $WEBSITETGZ"
+        NEWVERSION="$( webversion --file "${WEBSITEDIR}.new/public/static/version.json" )"
     fi
 
     if [ -n "$NEWVERSION" ] && [ "$NEWVERSION" == "$LATEST_VERSION" ]
@@ -103,6 +136,108 @@ main()
     else
         die "Versions do not match: new: \"$NEWVERSION\", expected: \"$LATEST_VERSION\""
     fi
+
+    return 0
+}
+
+
+###################################################################
+## Download and Update functions to download latest nighly       ##
+###################################################################
+
+download_nightly()
+{
+    echo "Getting latest nightly download location"
+    local LATEST_VERSION="$( webversion --nightly )" || die "Failed to retrieve the tag of the latest version"
+    local LATEST_URI="https://api.anaconda.org/download/MiiCam/miicamweb/${LATEST_VERSION}/MiiCamWeb-nightly-${LATEST_VERSION}.tar.gz"
+
+    echo "Removing older downloads"
+    [ -f "${WEBSITETGZ}" ] && rm "${WEBSITETGZ}"
+
+    echo "Downloading latest release files"
+    cd /tmp/sd
+    ${WGET} -q -t 5 -T 10 -O "${WEBSITETGZ}" -c "${LATEST_URI}" || die "Failed to download from $URL"
+
+    [ -f "${WEBSITETGZ}" ] || die "Failed to download ${WEBSITETGZ}"
+
+    return 0
+}
+
+verify_nightly()
+{
+    local ANACONDA_SUM="$( ${CURL} https://api.anaconda.org/package/MiiCam/MiiCamWeb/files | jq -r '. | to_entries[] | .value.md5' )"
+    local LOCAL_SUM="$( md5sum "${WEBSITETGZ}" | cut -d' ' -f1 )"
+
+    if [ "${ANACONDA_SUM}" == "${LOCAL_SUM}"]
+    then
+        echo "Sums OK: ${ANACONDA_SUM}"
+        return 0
+    else
+        echo "An error appeared during download: The sums don't match!"
+        echo "Sum on anaconda: ${ANACONDA_SUM}"
+        echo "Local Sum:       ${LOCAL_SUM}"
+        return 1
+    fi
+}
+
+update_nightly()
+{
+    echo "*** Downloading the latest webui release"
+    download_nightly
+    verify_nightly
+
+    ## Create the new webdir
+    test -d "${WEBSITEDIR}.new" && rm -rf "${WEBSITEDIR}.new"
+    mkdir "${WEBSITEDIR}.new" || die "*** Failed to create directory ${WEBSITEDIR}.new"
+
+    ## Remove the backup dest dir
+    test -d "${WEBSITEDIR}.old" && rm -rf "${WEBSITEDIR}.old"
+
+    ## Unpack the tarbal
+    if [ -f "$WEBSITETGZ" ]
+    then
+        echo "*** Unpacking $WEBSITETGZ"
+        tar xzf "$WEBSITETGZ" -C "${WEBSITEDIR}.new" || die "Failed to unpack $WEBSITETGZ"
+    fi
+
+    echo "*** Swapping downloaded web ui version with the current one"
+    mv "${WEBSITEDIR}" "${WEBSITEDIR}.old" && \
+    mv "${WEBSITEDIR}.new" "${WEBSITEDIR}" && \
+    echo "*** Update completed"
+
+    return 0
+}
+
+
+###################################################################
+## The main function                                             ##
+###################################################################
+
+main()
+{
+    case "$INPUT" in
+        --update)
+            update_release
+            ;;
+        --nightly)
+            update_nightly
+            ;;
+        --rollback)
+            rollback
+            ;;
+        *)
+            echo "Usage: $0 [--update|--nightly|--rollback]"
+            echo "Update the web interface if needed"
+            echo
+            echo "--update                - Check the version and download if required"
+            echo
+            echo "--rollback              - Rollback to the latest version (If possible)"
+            echo
+            echo "--nightly (Expert-only) - Download the latest nightly build"
+            exit 0
+        ;;
+    esac
+
 }
 
 main
diff --git a/sdcard/firmware/scripts/update/webversion b/sdcard/firmware/scripts/update/webversion
--- a/sdcard/firmware/scripts/update/webversion
+++ b/sdcard/firmware/scripts/update/webversion
@@ -2,6 +2,14 @@
 INPUT="$1"
 FILE="$2"
 
+## Set the curl command depending on local or camera
+if [ "$( uname -m )" == "armv5tel" ]
+then
+    CURL='curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -qs '
+else
+    CURL='curl -qs '
+fi
+
 fileversion()
 {
     local FILENAME="$1"
@@ -18,7 +26,6 @@ fileversion()
 }
 
 
-
 current()
 {
     ## Get version for web ui
@@ -26,9 +33,25 @@ current()
 }
 
 
+nightly()
+{
+    ## Get the latest nightly build of the web interface from anaconda
+    TAG="$( ${CURL} https://api.anaconda.org/package/MiiCam/MiiCamWeb/files | jq -r '. | to_entries[] .value.version'  | sort | tail -n 1 )"
+
+    if [ "x$TAG" == "x" ]
+    then
+        echo "Tag not found!"
+        exit 1
+    else
+        echo "$TAG"
+        exit 0
+    fi
+}
+
+
 latest()
 {
-    TAG="$( curl --cacert /tmp/sd/firmware/etc/ssl/cacert.pem -s https://api.github.com/repos/miicam/miicamweb/releases/latest | jq -r '.tag_name' )"
+    TAG="$( ${CURL} https://api.github.com/repos/miicam/miicamweb/releases/latest | jq -r '.tag_name' )"
 
     if [ "x$TAG" == "x" ]
     then
@@ -44,7 +67,7 @@ latest()
 usage()
 {
     echo "Retrieve the latest or current version tag of the web ui"
-    echo "Usage: $0 [--latest|--current|--file]"
+    echo "Usage: $0 [--latest|--current|--nightly|--file]"
     exit 0
 }
 
@@ -54,6 +77,9 @@ main()
     if [ "$INPUT" == "--current" ]
     then
         current
+    elif [ "$INPUT" == "--nightly" ]
+    then
+        nightly
     elif [ "$INPUT" == "--latest" ]
     then
         latest
